# 리액트 쿼리로 에러처리하기

## 용어 정리

- QueryCache: react query의 저장소 메커니즘. react query의 모든 데이터를 저장한다. 일반적으로 개발자가 직접 QueryCache에 접근할 일은 거의 없고 특정 cache에 접근하기 위해서는 QueryClient를 사용한다.
- Observer: 리액트 쿼리에서 하나의 캐시 entry를 감시하는 객체를 의미한다. 캐시 entry의 무언가가 변경되면 Observer가 알 수 있다. Observer를 생성하기 가장 쉬운 방법은 useQuery() 함수를 호출하는 것이다.

## onError

리액트 쿼리로 에러 처리를 할 때 가장 먼저 발견하게되는 것은 useQuery의 onError 옵션이다. onError 옵션으로 에러 핸들러를 넘겨 리액트 쿼리가 처리하도록 하는 것이다.

## 커스텀 에러 클래스 정의

커스텀 에러 클래스를 정의해보자.
커스텀인스턴스를 생성할 때 에러 핸들러를 등록하고 에러 바운더리에서 핸들러를 실행하도록 한다. 이런 방식을 사용하면 컴포넌트 level에서 에러 핸들러를 정의할 수 있으면서 핸들러도 단 한번만 실행된다.

1. 커스텀 에러 클래스 정의

```js
// CustomError.ts
export default class CustomError extends Error {
  name: string
  errorHandler: ErrorHandler

  constructor(message?: string, errorHandler?: ErrorHandler) {
    super(message)
    this.name = new.target.name
    // new 연산자로 호출된 생성자의 이름
    this.errorHandler = errorHandler
  }

  executeErrorHandler() {
    if (this.errorHandler) {
      this.errorHandler(this)
      // 에러 핸들러는 핸들링 대상 에러를 핸들러로 받음.
    }
  }
}
```

에러 인스턴스를 생성할 때 에러 핸들러도 같이 등록할 수 있게 했다. 등록된 에러 핸들러는 이후에 에러 바운더리 컴포넌트가 executeErrorHandler() 메서드를 호출함으로써 처리될 것이다.

2. useQuery 커스텀 훅 수정

```js
const getRecentFeeds = async (errorHandler: () => void) => {
  try {
    const { data } = await axios.get('/feeds/recent');

    return data;
  } catch(error) {
    throw new CustomError("recent 피드에서 에러발생!", errorHandler);
    // 여기서 throw된 에러는 에러 바운더리 컴포넌트까지 전파됨
  }
};

export default function useRecentFeeds(
  errorHandler: () => void,
) {
  return useQuery<Feed[], CustomError>('recentFeeds', () => getRecentFeeds(errorHandler), // 인자로 errorHandler를 전달.
  {
    useErrorBoundary: true,
  });
}
```

생략된 부분이 많지만 가장 중요한 코드만을 담았다. axios에서 throw된 에러를 잡아 커스텀 에러로 재가공해서 외부로 전파하였다.

3. 에러 바운더리에서 커스텀 에러 처리

```js
export default class ErrorBoundary extends Component<Props, State> {
  state: State = {
    hasError: false,
  }

  static getDerivedStateFromError(): State {
    return { hasError: true }
  }

  componentDidCatch(error: Error, errorInfo: ErrorInfo) {
    console.error("Uncaught error in Error Boundary:", error, errorInfo)

    if (error instanceof CustomError) {
      error.executeErrorHandler() // 1번 과정에서 커스텀 에러 클래스에 정의했던 에러 핸들러를 실행
    }
  }

  render() {
    if (this.state.hasError) {
      return this.props.fallback
    }

    return this.props.children
  }
}
```

CustomError 인스턴스를 생성할 때 넣어준 에러 핸들러를 에러 바운더리에서 처리해준다. 에러 바운더리가 에러를 처리하게 되면 바운더리가 감싸고 있는 컴포넌트들을 errorFallback 컴포넌트로 대체하므로 에러 핸들러는 무조건 한번만 실행된다.

## 결과

```js
//App.tsx
const App = () => {
  return (
    <ErrorBoundary fallback={<div>에러났어요~~</div>}>
      <RecentFeedsContent />
    </ErrorBoundary>
  );
};

//RecentFeedsContent.tsx
const RecentFeedsContent = () => {
  const { data: recentFeeds } = useRecentFeeds(() => {
    console.error('에러 처리 완료 with 에러 바운더리');
  });

  ...
```

위와 같이 구현하면 아래와 같은 장점이 있다.

- useQuery 커스텀 훅을 사용하는 컴포넌트에서 에러 핸들러를 정의할 수 있어 자유도가 높다. 같은 커스텀 훅을 사용하더라도 컴포넌트마다 다른 에러 처리 방법을 사용할 수 있다.
- 에러 바운더리의 선언적 에러 처리라는 이점을 그대로 가져갈 수 있다.
